export const dummyData = [
  {
    id: 1,
    title: 'Frontend mentor challenges',
    img: '/imgs/frontend mentor challenge.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 2,
    title: 'Typing speed test',
    img: '/imgs/typing speed test.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 3,
    title: 'book List',
    img: '/imgs/frontend mentor challenge.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 4,
    title: 'Frontend mentor',
    img: '/imgs/typing speed test.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 5,
    title: 'book List',
    img: '/imgs/frontend mentor challenge.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 6,
    title: 'Frontend mentor',
    img: '/imgs/typing speed test.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 7,
    title: 'book List',
    img: '/imgs/frontend mentor challenge.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 8,
    title: 'Frontend mentor',
    img: '/imgs/typing speed test.png',
    repo: '#',
    demo: '#',
    teqnologies: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
];

export const filters = [
  { type: 'all' },
  { type: 'vanillaJS' },
  { type: 'ReactJS' },
  { type: 'NextJs' },
  { type: 'Featured' },
];
