export const skills = [
  '/imgs/html.png',
  '/imgs/css.png',
  '/imgs/JavaScript.png',
  '/imgs/git.png',
  '/imgs/github.png',
  '/imgs/sass.png',
  '/imgs/tailwind.png',
  '/imgs/react.png',
  '/imgs/next.png',
  '/imgs/nodeJS.png',
  '/imgs/mongoDB.png',
  '/imgs/firebase.png',
];

export const dummyData = [
  {
    id: 1,
    title: 'Frontend mentor challenges',
    img: '/imgs/frontend mentor challenge.png',
    repo: '#',
    demo: '#',
    techs: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills small chalenged to improve my coding skills small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 2,
    title: 'Typing speed test',
    img: '/imgs/typing speed test.png',
    repo: '#',
    demo: '#',
    techs: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 3,
    title: 'book List',
    img: '/imgs/frontend mentor challenge.png',
    repo: '#',
    demo: '#',
    techs: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 4,
    title: 'Frontend mentor',
    img: '/imgs/typing speed test.png',
    repo: '#',
    demo: '#',
    techs: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
  {
    id: 5,
    title: 'Frontend mentor',
    img: '/imgs/typing speed test.png',
    repo: '#',
    demo: '#',
    techs: ['Html', 'CSS ', 'JS'],
    desc: 'small chalenged to improve my coding skills',
    category: 'vanillajs',
  },
];

export const filters = [
  { type: 'All' },
  { type: 'vanillajs' },
  { type: 'ReactJS' },
  { type: 'NextJS' },
  { type: 'Featured' },
];
